"""The starter-config emitter behind `dbmask init`.

A purpose-built emitter rather than a TOML-writer dependency: the generated config's
value is its comments (which pattern flagged each column, TODO markers where no v1
strategy fits), and no generic writer emits comments. Its output is parsed back by
`tomllib` in the unit tests, so the file it writes is always loadable.

init proposes, the operator decides. Every PII-flagged column gets a masking strategy,
never a silent `keep`: a false positive costs one explicit `keep` in review, a false
negative costs real PII in staging.
"""

from __future__ import annotations

import re
from contextlib import suppress
from dataclasses import dataclass
from pathlib import Path
from typing import Final

from .config import (
    DEFAULT_BATCH_SIZE,
    DEFAULT_CACHE_SIZE,
    DEFAULT_LOCALE,
    ColumnRule,
)
from .errors import DbmaskError, ErrorCode
from .introspect import PII_PATTERNS, ColumnInfo, SchemaModel, TableInfo
from .strategies import max_output_length

DEFAULT_SAFETY_PATTERN: Final = "_(staging|masked)$"
REDACT_VALUE: Final = "MASKED"

_BARE_KEY: Final = re.compile(r"^[A-Za-z0-9_-]+$")
_STRATEGY_FOR_PATTERN: Final = {pattern.label: pattern.strategy for pattern in PII_PATTERNS}


@dataclass(frozen=True, slots=True)
class Proposal:
    rule: ColumnRule
    comments: tuple[str, ...]


def propose(column: ColumnInfo, table: TableInfo) -> Proposal:
    """The strategy init suggests for one column, with the comments explaining it."""
    comments = []
    if column.pii is not None:
        comments.append(f'pii: name matches pattern "{column.pii}"')

    if column.name in table.primary_key or column.name in table.foreign_key_columns:
        if column.pii is not None:
            comments.append("key column: v1 requires keep so joins survive")
        return Proposal(_rule(column, "keep"), tuple(comments))
    if column.pii is None:
        return Proposal(_rule(column, "keep"), ())

    unique = bool(table.unique_indexes_covering(column.name))
    proposed = _STRATEGY_FOR_PATTERN[column.pii]
    if proposed == "null" or not column.is_text:
        if column.nullable:
            return Proposal(_rule(column, "null"), tuple(comments))
        comments.append(f"TODO review: {column.type_name} is NOT NULL and has no v1 strategy")
        return Proposal(_rule(column, "keep"), tuple(comments))

    # First candidate whose worst-case output fits the column, so `init` output always
    # passes `check`. redact is the universal fallback because its length is chosen here.
    for candidate in (proposed, "redact"):
        rule = _rule(column, candidate, unique=unique)
        budget = max_output_length(rule)
        if column.length is None or budget is None or budget <= column.length:
            if candidate != proposed:
                comments.append(f'TODO review: "{proposed}" does not fit {column.type_name}')
            return Proposal(rule, tuple(comments))

    comments.append(f"TODO review: no v1 strategy fits {column.type_name}")
    return Proposal(_rule(column, "keep"), tuple(comments))


def _rule(column: ColumnInfo, strategy: str, unique: bool = False) -> ColumnRule:
    return ColumnRule(
        table=column.table,
        column=column.name,
        strategy=strategy,
        value=REDACT_VALUE if strategy == "redact" else None,
        unique=unique and strategy not in ("keep", "null"),
    )


def render_config(schema: SchemaModel) -> str:
    """The full starter config as TOML text, comments included."""
    proposals = {
        name: {column: propose(info, table) for column, info in table.columns.items()}
        for name, table in schema.tables.items()
    }
    flagged = sum(1 for column in schema.columns() if column.pii is not None)
    lines = [
        f'# Generated by dbmask init from the {schema.dialect} database "{schema.database}".',
        "# Review every line before the first mask: init proposes, you decide.",
        f"# {len(schema.tables)} tables, {len(schema.columns())} columns, "
        f"{flagged} flagged by name pattern.",
        "",
        "[project]",
        f'locale = "{DEFAULT_LOCALE}"',
        "",
        "[safety]",
        "# dbmask refuses to mask a database whose name does not match this pattern.",
        f"database_name_pattern = {_string(_safety_pattern(schema.database))}",
        "",
        "[settings]",
        f"batch_size = {DEFAULT_BATCH_SIZE}",
        f"cache_size = {DEFAULT_CACHE_SIZE}",
    ]
    for name in sorted(proposals):
        lines += ["", f"[tables.{_key(name)}.columns]"]
        lines += _table_lines(proposals[name])
    lines += [
        "",
        "# Logical joins that no foreign key enforces are re-checked after every run.",
        "# Add one block per pair, for example:",
        "# [[verify.joins]]",
        '# left  = "users.email"',
        '# right = "orders.customer_email"',
        "",
    ]
    return "\n".join(lines)


def _safety_pattern(database: str) -> str:
    """The default pattern, or one anchored to this database when the default misses it."""
    if re.search(DEFAULT_SAFETY_PATTERN, database):
        return DEFAULT_SAFETY_PATTERN
    return f"^{re.escape(database)}$"


def _table_lines(proposals: dict[str, Proposal]) -> list[str]:
    width = max((len(_key(column)) for column in proposals), default=0)
    lines: list[str] = []
    for column, proposal in proposals.items():
        lines += [f"# {comment}" for comment in proposal.comments]
        lines.append(f"{_key(column).ljust(width)} = {_value(proposal.rule)}")
    return lines


def _value(rule: ColumnRule) -> str:
    options = []
    if rule.value is not None:
        options.append(f"value = {_string(rule.value)}")
    if rule.unique:
        options.append("unique = true")
    if not options:
        return _string(rule.strategy)
    return "{ strategy = " + _string(rule.strategy) + ", " + ", ".join(options) + " }"


def _key(name: str) -> str:
    return name if _BARE_KEY.match(name) else _string(name)


def _string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def write_config(path: Path, text: str, force: bool) -> None:
    """Write the starter config, refusing to overwrite a reviewed file without --force.

    The write is atomic: a temporary file in the same directory is renamed over the
    target. Writing in place would truncate the operator's reviewed config first, so a
    full disk or a kill halfway through would leave a half-written file that still parses
    as TOML, silently dropping the columns below the cut.
    """
    if path.exists() and not force:
        raise DbmaskError(
            ErrorCode.E_CONFIG,
            f'"{path}" already exists; pass --force to overwrite it or choose another -o path',
        )
    temporary = path.with_name(f".{path.name}.dbmask-tmp")
    try:
        temporary.write_text(text, encoding="utf-8")
        temporary.replace(path)
    except OSError as exc:
        with suppress(OSError):
            temporary.unlink(missing_ok=True)
        raise DbmaskError(
            ErrorCode.E_CONFIG, f'cannot write "{path}": {type(exc).__name__}'
        ) from None
